language: java
sudo: true
jdk: openjdk8
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_5434d186515e_key -iv $encrypted_5434d186515e_iv
  -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- ./gradlew jacocoTestReport coveralls
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false
