name: 'Gradle Wrapper Validation'
description: 'Validates Gradle Wrapper JAR Files'
author: 'Gradle'

inputs:
  min-wrapper-count:
    description: 'Minimum expected wrapper JAR files'
    required: false
    default: '1'
  allow-snapshots:
    description: 'Allow snapshot Gradle versions'
    required: false
    default: 'false'
  allow-checksums:
    description: 'Allow arbitrary checksums, comma separated'
    required: false
    default: ''

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'shield'
  color: gray-dark
