os: osx
osx_image: xcode10.2
language: cpp
script:
  - ./gradlew --console plain --project-dir cpp/composite-build build
  - ./gradlew --console plain --project-dir cpp/transitive-dependencies build
  - ./gradlew --console plain --project-dir cpp/simple-library build
  - ./gradlew --console plain --project-dir swift/composite-build build
  - ./gradlew --console plain --project-dir swift/transitive-dependencies build
  - ./gradlew --console plain --project-dir swift/simple-library build
