language: java
install: true

jdk:
  - openjdk8

jobs:
  include:
    - name: "Play 2.3.10 Integration Tests"
      env: GRADLE_TASK=integrationTest PLAY_VERSION=2.3.10
    - name: "Play 2.4.11 Integration Tests"
      env: GRADLE_TASK=integrationTest PLAY_VERSION=2.4.11
    - name: "Play 2.5.19 Integration Tests"
      env: GRADLE_TASK=integrationTest PLAY_VERSION=2.5.19
    - name: "Play 2.6.25 Integration Tests"
      env: GRADLE_TASK=integrationTest PLAY_VERSION=2.6.25
    - name: "Play 2.7.5 Integration Tests"
      env: GRADLE_TASK=integrationTest PLAY_VERSION=2.7.5
    - name: "Documentation Tests"
      env: GRADLE_TASK=docTest PLAY_VERSION=not_used

script:
  - ./gradlew -Pplayframework.int-test.target.version=$PLAY_VERSION $GRADLE_TASK -s --continue

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
