/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.test;

import org.test.optional.OptionalFeature;

public class Consumer {
    public boolean someConsumerMethod() {
        return true;
    }

    public boolean canUseLibrary() {
        return new Library().someLibraryMethod();
    }

    public int canUseOptionalFeature() {
        return OptionalFeature.lastIndexOf("foofoofoo", "foo");
    }
}
