trigger:
  branches:
    include:
      - 2.x
  tags:
    include:
      - '*'

stages:
  - stage: test_core
    jobs:
      - job: jvm_and_linux
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: './ci/install-jdk10.sh'
          - task: Gradle@2
            inputs:
              tasks: 'spek-runner-junit5:check integration-test:check'
              options: '--stacktrace -PexcludeIdePlugins'
      - job: macos
        pool:
          vmImage: 'macOS-10.14'
        steps:
          - script: './ci/install-jdk10.sh'
          - task: Gradle@2
            inputs:
              tasks: 'integration-test:check'
              options: '--stacktrace -PexcludeIdePlugins'
      - job: windows
        pool:
          vmImage: 'win1803'
        steps:
          - task: PowerShell@2
            inputs:
              filePath: '.\ci\install-jdk10.ps1'
          - task: Gradle@2
            inputs:
              tasks: 'integration-test:check'
              options: '--stacktrace -PexcludeIdePlugins'

  - stage: test_ide_plugins
    dependsOn: test_core
    condition: succeeded()
    jobs:
      - job: intellij_idea
        pool:
          vmImage: 'ubuntu-16.04'
        strategy:
          matrix:
            ij182:
              ij_sdk: IJ182
            ij183:
              ij_sdk: IJ183
            ij191:
              ij_sdk: IJ191
            ij192:
              ij_sdk: IJ192
        steps:
          - script: './ci/install-jdk10.sh'
          - task: Gradle@2
            inputs:
              tasks: 'spek-ide-plugin-intellij-idea:buildPlugin'
              options: '--stacktrace -Pij.version=$(ij_sdk)'
      - job: android_studio
        pool:
          vmImage: 'ubuntu-16.04'
        strategy:
          matrix:
            as33:
              as_sdk: AS33
            as34:
              as_sdk: AS34
            as35:
              as_sdk: AS35
        steps:
          - script: './ci/install-jdk10.sh'
          - task: Gradle@2
            inputs:
              tasks: 'spek-ide-plugin-android-studio:buildPlugin'
              options: '--stacktrace -Pas.version=$(as_sdk)'

  - stage: release
    dependsOn: test_ide_plugins
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), or(eq(variables['Build.SourceBranch'], 'refs/heads/2.x'), startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - job: jvm_js_and_linux
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: './ci/install-jdk10.sh'
          - task: Gradle@2
            env:
              BINTRAY_USER: $(BINTRAY_USER)
              BINTRAY_API_KEY: $(BINTRAY_API_KEY)
            inputs:
              tasks: 'spek-dsl:bintrayUpload spek-runtime:bintrayUpload spek-runner-junit5:bintrayUpload'
              options: '--stacktrace -PexcludeIdePlugins'
      - job: macos
        pool:
          vmImage: 'macOS-10.14'
        steps:
          - script: './ci/install-jdk10.sh'
          - task: Gradle@2
            env:
              BINTRAY_USER: $(BINTRAY_USER)
              BINTRAY_API_KEY: $(BINTRAY_API_KEY)
            inputs:
              tasks: 'spek-dsl:bintrayUpload'
              options: '--stacktrace -PexcludeIdePlugins'
      - job: windows
        pool:
          vmImage: 'win1803'
        steps:
          - task: PowerShell@2
            inputs:
              filePath: '.\ci\install-jdk10.ps1'
          - task: Gradle@2
            env:
              BINTRAY_USER: $(BINTRAY_USER)
              BINTRAY_API_KEY: $(BINTRAY_API_KEY)
            inputs:
              tasks: 'spek-dsl:bintrayUpload'
              options: '--stacktrace -PexcludeIdePlugins'
      - job: intellij_idea_plugins
        pool:
          vmImage: 'ubuntu-16.04'
        strategy:
          matrix:
            ij182:
              ij_sdk: IJ182
            ij183:
              ij_sdk: IJ183
            ij191:
              ij_sdk: IJ191
            ij192:
              ij_sdk: IJ192
        steps:
          - script: './ci/install-jdk10.sh'
          - task: Gradle@2
            env:
              HUB_API_TOKEN: $(HUB_API_TOKEN)
            inputs:
              tasks: 'spek-ide-plugin-intellij-idea:publishPlugin'
              options: '--stacktrace -Pij.version=$(ij_sdk)'
      - job: android_studio_plugins
        pool:
          vmImage: 'ubuntu-16.04'
        strategy:
          matrix:
            as33:
              as_sdk: AS33
            as34:
              as_sdk: AS34
            as35:
              as_sdk: AS35
        steps:
          - script: './ci/install-jdk10.sh'
          - task: Gradle@2
            env:
              HUB_API_TOKEN: $(HUB_API_TOKEN)
            inputs:
              tasks: 'spek-ide-plugin-android-studio:publishPlugin'
              options: '--stacktrace -Pas.version=$(as_sdk)'

  - stage: update
    dependsOn: release
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - job: docs
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: curl -X POST -d '' $NETLIFY_DEPLOY_URL
            env:
              NETLIFY_DEPLOY_URL: $(NETLIFY_DEPLOY_URL)

