/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.6.1/userguide/java_library_plugin.html
 */

plugins {
    `java-library`
    `maven-publish`
    `signing`
}

group = "org.test"
version = "0.0.1"

repositories {
    jcenter()
}

dependencies {
    api("org.apache.commons:commons-math3:3.6.1")

    implementation("com.google.guava:guava:28.0-jre")

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.4.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.4.2")
}

val test by tasks.getting(Test::class) {
    // Use junit platform for unit tests
    useJUnitPlatform()
}

publishing {
    publications {
        create<MavenPublication>("main") {
            from(components["java"])
        }
    }

    repositories {
        maven {
            name = "artifactory"
            url = uri("http://localhost:8081/artifactory/example-repo-local")
        }
        maven {
            name = "testRepo"
            url = uri("$buildDir/repo")
        }
    }
}

signing {
    setRequired({ !version.toString().endsWith("-SNAPSHOT") })
    useGpgCmd()
    sign(publishing.publications["main"])
}