/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.test;

/**
 * A great library, used by many projects!
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
